_target_: src.logger.CometMLWriter
project_name: "pytorch_template_asr_example"
workspace: null
run_name: "DF_substitute_SMN"
mode: "online"

log_to_local: True
local_log_filename: "metrics.jsonl"
local_summary_filename: "metrics_latest.csv"

loss_names:
  - loss
  - gen_loss
  - disc_loss
  - adv_loss
  - fm_loss
  - mel_spec_loss
  - stft_loss
  - mpd_disc_loss
  - msd_disc_loss

log_checkpoints: False
id_length: 32